# Generated by Django 6.0.7 on 2026-07-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='submission_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='submission_email_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='submission_imap_host',
            field=models.CharField(blank=True, default='imap.hostinger.com', max_length=100, null=True),
        ),
    ]
