# Generated by Django 6.0.7 on 2026-07-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_submission_email_user_submission_email_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='official_email',
            field=models.EmailField(blank=True, help_text='Assigned by office once fees are paid', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(blank=True, help_text="Student's own email, separate from login email", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pg_college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pg_degree',
            field=models.CharField(blank=True, help_text='e.g. M.E. Software Engineering — leave blank if not applicable', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pg_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pg_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tenth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tenth_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tenth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twelfth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twelfth_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twelfth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ug_college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ug_degree',
            field=models.CharField(blank=True, help_text='e.g. B.E. Computer Science', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ug_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ug_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
