# Generated by Django 6.0.7 on 2026-07-31 05:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_official_email_user_personal_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree_certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenth_marksheet',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AddField(
            model_name='user',
            name='twelfth_marksheet',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
