# Generated by Django 6.0.7 on 2026-08-01 06:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_degree_certificate_user_tenth_marksheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_conditions_doc',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Signed Terms & Conditions (student)', max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AddField(
            model_name='user',
            name='trainer_certificate',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Trainer's certificate/resume", max_length=255, null=True, verbose_name='raw'),
        ),
    ]
