# Generated by Django 6.0.7 on 2026-08-01 07:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_terms_conditions_doc_user_trainer_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_certificate',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Trainer's work experience certificate", max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AddField(
            model_name='user',
            name='pg_certificate',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='PG degree certificate', max_length=255, null=True, verbose_name='raw'),
        ),
    ]
