# Generated by Django 6.0.7 on 2026-07-31 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_age', models.PositiveIntegerField(help_text='Maximum eligible age for this course')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('education_summary', models.CharField(blank=True, help_text='e.g. B.E. CSE, 2024 pass-out', max_length=300, null=True)),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('walk_in', 'Walk-in'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('converted', 'Converted')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='admissions.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
