# Generated by Django 6.0.7 on 2026-07-31 11:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, help_text='Course fee before GST', max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('plan_type', models.CharField(choices=[('full', 'Full Payment'), ('emi', 'EMI')], default='full', max_length=10)),
                ('installment_count', models.PositiveIntegerField(default=1, help_text='1 for full payment, 2+ for EMI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='admissions.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='admissions.payment')),
            ],
            options={
                'ordering': ['installment_number'],
                'unique_together': {('payment', 'installment_number')},
            },
        ),
    ]
