# Generated by Django 6.0.7 on 2026-08-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_enquiry_address_welcomekit'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
