# Generated by Django 6.0.7 on 2026-08-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_enquiry_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='created_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
