# Generated by Django 6.0.7 on 2026-07-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10),
        ),
    ]
