# Generated by Django 6.0.7 on 2026-07-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0008_batch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='planned_topics',
            field=models.TextField(blank=True, help_text='Comma-separated list of topics planned for this batch', null=True),
        ),
    ]
