# Generated by Django 6.0.7 on 2026-07-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0010_mockinterviewsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewsession',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
