# Generated by Django 6.0.7 on 2026-07-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0011_mockinterviewsession_scheduled_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='max_students',
            field=models.PositiveIntegerField(default=45),
        ),
    ]
