# Generated by Django 6.0.7 on 2026-07-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0012_batch_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='course_name',
            field=models.CharField(blank=True, help_text='e.g. AI FULLSTACK', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='programming_language',
            field=models.CharField(blank=True, help_text='e.g. Java, Python', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='training_mode',
            field=models.CharField(default='Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='batch',
            name='planned_topics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
