# Generated by Django 6.0.7 on 2026-07-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0013_batch_course_name_batch_programming_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.CharField(choices=[('task', 'Daily Task'), ('mini_project', 'Mini Project'), ('main_project', 'Main Project')], default='task', max_length=15),
        ),
    ]
