# Generated by Django 6.0.7 on 2026-07-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0014_assignment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(),
        ),
    ]
