# Generated by Django 6.0.7 on 2026-07-30 06:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0016_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='attachment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
