# Generated by Django 6.0.7 on 2026-07-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0017_assignmentsubmission_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(choices=[('leave', 'Leave Request'), ('doubt', 'Doubt Clarification'), ('general', 'General')], default='general', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='leave_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='leave_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
