# Generated by Django 6.0.7 on 2026-07-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0018_message_category_message_leave_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewsession',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
