# Generated by Django 6.0.7 on 2026-08-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0019_mockinterviewsession_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='class_start_time',
            field=models.TimeField(blank=True, help_text='Daily class start time', null=True),
        ),
    ]
