# Generated by Django 6.0.7 on 2026-08-03 07:01

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0020_batch_class_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='cc_email',
            field=models.CharField(blank=True, help_text='Comma-separated CC addresses used at submission time', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='links',
            field=models.TextField(blank=True, help_text='GitHub/Drive links, one per line', null=True),
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='attachment')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='trainer_ai.assignmentsubmission')),
            ],
        ),
    ]
