# Generated by Django 6.0.7 on 2026-08-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0022_classrecording_enrollment_recordingview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecording',
            name='link',
            field=models.URLField(help_text='Google Drive / YouTube (unlisted) / Zoom cloud / Microsoft Teams recording link', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mockinterviewsession',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
