# Generated by Django 6.0.7 on 2026-08-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0024_absencenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='category',
            field=models.CharField(choices=[('task', 'Daily Task'), ('mini_project', 'Mini Project'), ('main_project', 'Main Project'), ('seminar', 'Seminar')], default='task', max_length=15),
        ),
    ]
