# Generated by Django 6.0.7 on 2026-08-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0025_alter_assignment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
