# Generated by Django 6.0.7 on 2026-08-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0027_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='trainer_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
