# Generated by Django 6.0.7 on 2026-08-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_ai', '0028_batch_trainer_notified_batch_welcome_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='class_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
